// <auto-generated />
using System;
using HW.Host.API.Infrastructure.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HW.Host.API.Infrastructure.Migrations
{
    [DbContext(typeof(HWHostDbContext))]
    [Migration("20201201031414_Add_Table_HW_PhoneModelInfo")]
    partial class Add_Table_HW_PhoneModelInfo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HW.Host.API.Model.DefaultEntity.HW_Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdminName")
                        .IsRequired();

                    b.Property<string>("AdminPwd")
                        .IsRequired();

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.HasKey("Id");

                    b.ToTable("HW_Admin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdminName = "Admin",
                            AdminPwd = "Admin123456",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 19, DateTimeKind.Local).AddTicks(4895),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 20, DateTimeKind.Local).AddTicks(7815)
                        },
                        new
                        {
                            Id = 2,
                            AdminName = "Mr.Fang",
                            AdminPwd = "Fh2269...",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 20, DateTimeKind.Local).AddTicks(9542),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 20, DateTimeKind.Local).AddTicks(9544)
                        });
                });

            modelBuilder.Entity("HW.Host.API.Model.DefaultEntity.HW_Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.Property<string>("UserPwd")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("HW_Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(2024),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(2027),
                            UserName = "Admin",
                            UserPwd = "Admin123456"
                        },
                        new
                        {
                            Id = 2,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(3349),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(3351),
                            UserName = "Mr.Fang",
                            UserPwd = "Fh2269..."
                        });
                });

            modelBuilder.Entity("HW.Host.API.Model.ModelEntity.HW_BackGroundImageInfo", b =>
                {
                    b.Property<int>("BGId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BGUrl");

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.HasKey("BGId");

                    b.ToTable("HW_BackGroundImageInfo");

                    b.HasData(
                        new
                        {
                            BGId = 1,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg1.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(5881),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(5883)
                        },
                        new
                        {
                            BGId = 2,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg2.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(6950),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(6952)
                        },
                        new
                        {
                            BGId = 3,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg3.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7026),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7027)
                        },
                        new
                        {
                            BGId = 4,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg4.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7040),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7041)
                        },
                        new
                        {
                            BGId = 5,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg5.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7052),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7053)
                        },
                        new
                        {
                            BGId = 6,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg6.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7068),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7068)
                        },
                        new
                        {
                            BGId = 7,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg7.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7080),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7080)
                        },
                        new
                        {
                            BGId = 8,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg8.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7092),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7092)
                        },
                        new
                        {
                            BGId = 9,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg9.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7103),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7104)
                        },
                        new
                        {
                            BGId = 10,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg10.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7116),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7116)
                        },
                        new
                        {
                            BGId = 11,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg11.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7129),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7129)
                        },
                        new
                        {
                            BGId = 12,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg12.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7141),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7142)
                        },
                        new
                        {
                            BGId = 13,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg13.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7153),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7154)
                        },
                        new
                        {
                            BGId = 14,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg14.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7165),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7166)
                        },
                        new
                        {
                            BGId = 15,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg15.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7177),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7178)
                        },
                        new
                        {
                            BGId = 16,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg16.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7189),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7189)
                        },
                        new
                        {
                            BGId = 17,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg17.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7230),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7231)
                        },
                        new
                        {
                            BGId = 18,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg18.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7244),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7244)
                        },
                        new
                        {
                            BGId = 19,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg19.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7256),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7256)
                        },
                        new
                        {
                            BGId = 20,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg20.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7268),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7268)
                        },
                        new
                        {
                            BGId = 21,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg21.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7280),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7280)
                        },
                        new
                        {
                            BGId = 22,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg22.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7291),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7292)
                        },
                        new
                        {
                            BGId = 23,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg23.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7304),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7304)
                        },
                        new
                        {
                            BGId = 24,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg24.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7315),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7316)
                        },
                        new
                        {
                            BGId = 25,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg25.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7327),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7328)
                        },
                        new
                        {
                            BGId = 26,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg26.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7339),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7340)
                        },
                        new
                        {
                            BGId = 27,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg27.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7351),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7351)
                        },
                        new
                        {
                            BGId = 28,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg28.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7363),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7363)
                        },
                        new
                        {
                            BGId = 29,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg29.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7374),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7375)
                        },
                        new
                        {
                            BGId = 30,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg30.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7413),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7414)
                        },
                        new
                        {
                            BGId = 31,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg31.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7425),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7426)
                        },
                        new
                        {
                            BGId = 32,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg32.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7437),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7437)
                        },
                        new
                        {
                            BGId = 33,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg33.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7448),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7449)
                        },
                        new
                        {
                            BGId = 34,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg34.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7461),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7462)
                        },
                        new
                        {
                            BGId = 35,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg35.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7473),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7474)
                        },
                        new
                        {
                            BGId = 36,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg36.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7485),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7486)
                        },
                        new
                        {
                            BGId = 37,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg37.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7497),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7498)
                        },
                        new
                        {
                            BGId = 38,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg38.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7509),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7509)
                        },
                        new
                        {
                            BGId = 39,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg39.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7520),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7521)
                        },
                        new
                        {
                            BGId = 40,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg40.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7532),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7533)
                        },
                        new
                        {
                            BGId = 41,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg41.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7544),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7545)
                        },
                        new
                        {
                            BGId = 42,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg42.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7556),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7556)
                        },
                        new
                        {
                            BGId = 43,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg43.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7621),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7622)
                        },
                        new
                        {
                            BGId = 44,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg44.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7634),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7635)
                        },
                        new
                        {
                            BGId = 45,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg45.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7646),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7646)
                        },
                        new
                        {
                            BGId = 46,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg46.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7657),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7658)
                        },
                        new
                        {
                            BGId = 47,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg47.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7669),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7670)
                        },
                        new
                        {
                            BGId = 48,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg48.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7681),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7681)
                        },
                        new
                        {
                            BGId = 49,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg49.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7693),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7693)
                        },
                        new
                        {
                            BGId = 50,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg50.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7704),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7705)
                        },
                        new
                        {
                            BGId = 51,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg51.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7716),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7717)
                        },
                        new
                        {
                            BGId = 52,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg52.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7728),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7728)
                        },
                        new
                        {
                            BGId = 53,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg53.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7739),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7740)
                        },
                        new
                        {
                            BGId = 54,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg54.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7751),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7752)
                        },
                        new
                        {
                            BGId = 55,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg55.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7763),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7764)
                        },
                        new
                        {
                            BGId = 56,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg56.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7775),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7775)
                        },
                        new
                        {
                            BGId = 57,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg57.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7848),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7849)
                        },
                        new
                        {
                            BGId = 58,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg58.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7862),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7863)
                        },
                        new
                        {
                            BGId = 59,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg59.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7874),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7875)
                        },
                        new
                        {
                            BGId = 60,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg60.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7886),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7886)
                        },
                        new
                        {
                            BGId = 61,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg61.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7897),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7898)
                        },
                        new
                        {
                            BGId = 62,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg62.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7909),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7910)
                        },
                        new
                        {
                            BGId = 63,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg63.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7921),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7922)
                        },
                        new
                        {
                            BGId = 64,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg64.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7933),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7933)
                        },
                        new
                        {
                            BGId = 65,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg65.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7945),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7945)
                        },
                        new
                        {
                            BGId = 66,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg66.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7958),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7958)
                        },
                        new
                        {
                            BGId = 67,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg67.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7970),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7970)
                        },
                        new
                        {
                            BGId = 68,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg68.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7981),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(7982)
                        },
                        new
                        {
                            BGId = 69,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg69.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8019),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8020)
                        },
                        new
                        {
                            BGId = 70,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg70.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8032),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8033)
                        },
                        new
                        {
                            BGId = 71,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg71.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8063),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8064)
                        },
                        new
                        {
                            BGId = 72,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg72.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8075),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8076)
                        },
                        new
                        {
                            BGId = 73,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg73.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8087),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8087)
                        },
                        new
                        {
                            BGId = 74,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg74.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8099),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8099)
                        },
                        new
                        {
                            BGId = 75,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg75.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8110),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8111)
                        },
                        new
                        {
                            BGId = 76,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg76.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8122),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8122)
                        },
                        new
                        {
                            BGId = 77,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg77.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8134),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8134)
                        },
                        new
                        {
                            BGId = 78,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg78.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8146),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8146)
                        },
                        new
                        {
                            BGId = 79,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg79.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8157),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8158)
                        },
                        new
                        {
                            BGId = 80,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg80.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8169),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8170)
                        },
                        new
                        {
                            BGId = 81,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg81.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8181),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8181)
                        },
                        new
                        {
                            BGId = 82,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg82.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8273),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8273)
                        },
                        new
                        {
                            BGId = 83,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg83.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8308),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8308)
                        },
                        new
                        {
                            BGId = 84,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg84.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8320),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8320)
                        },
                        new
                        {
                            BGId = 85,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg85.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8331),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8331)
                        },
                        new
                        {
                            BGId = 86,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg86.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8342),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8342)
                        },
                        new
                        {
                            BGId = 87,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg87.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8353),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8354)
                        },
                        new
                        {
                            BGId = 88,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg88.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8364),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8365)
                        },
                        new
                        {
                            BGId = 89,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg89.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8375),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8375)
                        },
                        new
                        {
                            BGId = 90,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg90.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8386),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8387)
                        },
                        new
                        {
                            BGId = 91,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg91.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8398),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8398)
                        },
                        new
                        {
                            BGId = 92,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg92.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8408),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8409)
                        },
                        new
                        {
                            BGId = 93,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg93.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8420),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8420)
                        },
                        new
                        {
                            BGId = 94,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg94.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8431),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8431)
                        },
                        new
                        {
                            BGId = 95,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg95.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8442),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8442)
                        },
                        new
                        {
                            BGId = 96,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg96.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8453),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8453)
                        },
                        new
                        {
                            BGId = 97,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg97.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8464),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8464)
                        },
                        new
                        {
                            BGId = 98,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg98.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8500),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8501)
                        },
                        new
                        {
                            BGId = 99,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg99.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8511),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8512)
                        },
                        new
                        {
                            BGId = 100,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg100.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8522),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(8523)
                        });
                });

            modelBuilder.Entity("HW.Host.API.Model.ModelEntity.HW_CopywritingInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.HasKey("Id");

                    b.ToTable("HW_CopywritingInfo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "当你的能力还撑不起你的野心的时，你就需要静下心来 好好学习。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(4207),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(4209)
                        },
                        new
                        {
                            Id = 2,
                            Content = "脏的人多了，干净反倒成了一种错。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(5042),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(5044)
                        },
                        new
                        {
                            Id = 3,
                            Content = "你羡慕的生活都是你没熬过的苦。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(5052),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(5053)
                        },
                        new
                        {
                            Id = 4,
                            Content = "所谓天才，只不过是把别人喝咖啡的功夫都用在了工作上了。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(5054),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(5055)
                        },
                        new
                        {
                            Id = 5,
                            Content = "生活便是寻求新的知识。——门捷列夫",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(5056),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(5057)
                        },
                        new
                        {
                            Id = 6,
                            Content = "如果你浪费了自己的年龄，那是挺可悲的。因为你的青春只能持续一点儿时间——很短的一点儿时间。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(5058),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(5059)
                        },
                        new
                        {
                            Id = 7,
                            Content = "世界上一成不变的东西，只有“任何事物都是在不断变化的”这条真理。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(5059),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 14, 21, DateTimeKind.Local).AddTicks(5060)
                        });
                });

            modelBuilder.Entity("HW.Host.API.Model.ModelEntity.HW_EmailHistoryInfo", b =>
                {
                    b.Property<int>("EHID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<string>("EmailBody")
                        .IsRequired();

                    b.Property<string>("EmailCode");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.Property<string>("RecipientId")
                        .IsRequired();

                    b.HasKey("EHID");

                    b.ToTable("HW_EmailHistoryInfo");
                });

            modelBuilder.Entity("HW.Host.API.Model.ModelEntity.HW_PhoneModelInfo", b =>
                {
                    b.Property<int>("PhoneID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PhoneCode")
                        .IsRequired();

                    b.Property<string>("PhoneColour")
                        .IsRequired();

                    b.Property<string>("PhoneFineness")
                        .IsRequired();

                    b.Property<int>("PhoneIsReturn");

                    b.Property<DateTime>("PhoneLeaseTime");

                    b.Property<string>("PhoneName")
                        .IsRequired();

                    b.Property<int>("PhonePrice");

                    b.Property<string>("PhoneRAM")
                        .IsRequired();

                    b.Property<string>("PhoneRemarks");

                    b.Property<string>("PhoneReturnRemarks");

                    b.Property<DateTime>("PhoneReturnTime");

                    b.HasKey("PhoneID");

                    b.ToTable("HW_PhoneModelInfo");

                    b.HasData(
                        new
                        {
                            PhoneID = 1,
                            PhoneCode = "862754045574919",
                            PhoneColour = "红",
                            PhoneFineness = "95",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "VIVO X23",
                            PhonePrice = 1000,
                            PhoneRAM = "8+128",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PhoneID = 2,
                            PhoneCode = "860450040094555",
                            PhoneColour = "黑",
                            PhoneFineness = "靓",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "华为畅享Z 5G",
                            PhonePrice = 1250,
                            PhoneRAM = "6+64",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PhoneID = 3,
                            PhoneCode = "861189053704549",
                            PhoneColour = "蓝",
                            PhoneFineness = "靓",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "华为畅享20Pro 5G",
                            PhonePrice = 1600,
                            PhoneRAM = "6+128",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PhoneID = 4,
                            PhoneCode = "866216030724606",
                            PhoneColour = "粉",
                            PhoneFineness = "靓",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "华为Mate10 Pro",
                            PhonePrice = 1000,
                            PhoneRAM = "6+64",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PhoneID = 5,
                            PhoneCode = "868034039428685",
                            PhoneColour = "黑",
                            PhoneFineness = "9",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "华为Mate10 Pro",
                            PhonePrice = 950,
                            PhoneRAM = "6+128",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PhoneID = 6,
                            PhoneCode = "865043042963151",
                            PhoneColour = "蓝",
                            PhoneFineness = "9",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "华为Mate20",
                            PhonePrice = 1200,
                            PhoneRAM = "6+64",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PhoneID = 7,
                            PhoneCode = "868577030922627",
                            PhoneColour = "黑",
                            PhoneFineness = "95",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "华为P20Pro",
                            PhonePrice = 1050,
                            PhoneRAM = "6+64",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PhoneID = 8,
                            PhoneCode = "864928040295179",
                            PhoneColour = "蓝",
                            PhoneFineness = "95",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "华为Nova5i",
                            PhonePrice = 1200,
                            PhoneRAM = "8+128",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PhoneID = 9,
                            PhoneCode = "862474042226765",
                            PhoneColour = "黑",
                            PhoneFineness = "靓",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "华为P30",
                            PhonePrice = 1800,
                            PhoneRAM = "8+64",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PhoneID = 10,
                            PhoneCode = "860133058133412",
                            PhoneColour = "黑",
                            PhoneFineness = "靓",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "华为Nova7SE5G",
                            PhonePrice = 2100,
                            PhoneRAM = "8+128",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PhoneID = 11,
                            PhoneCode = "861594045284619",
                            PhoneColour = "粉",
                            PhoneFineness = "靓",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "华为P20",
                            PhonePrice = 1100,
                            PhoneRAM = "6+128",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PhoneID = 12,
                            PhoneCode = "99001343870346",
                            PhoneColour = "黑",
                            PhoneFineness = "95",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "小米9",
                            PhonePrice = 1500,
                            PhoneRAM = "8+128",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PhoneID = 13,
                            PhoneCode = "99001332374714",
                            PhoneColour = "蓝",
                            PhoneFineness = "9",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "小米9",
                            PhonePrice = 1150,
                            PhoneRAM = "6+128",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PhoneID = 14,
                            PhoneCode = "99001583306158",
                            PhoneColour = "白",
                            PhoneFineness = "靓",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "小米10青春版",
                            PhonePrice = 1700,
                            PhoneRAM = "8+128",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PhoneID = 15,
                            PhoneCode = "99001302146726",
                            PhoneColour = "白",
                            PhoneFineness = "靓",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "红米K20Pro",
                            PhonePrice = 1450,
                            PhoneRAM = "8+128",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
