// <auto-generated />
using System;
using HW.Host.API.Infrastructure.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HW.Host.API.Infrastructure.Migrations
{
    [DbContext(typeof(HWHostDbContext))]
    [Migration("20201130084952_Update_TableName")]
    partial class Update_TableName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HW.Host.API.Model.DefaultEntity.HW_Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdminName")
                        .IsRequired();

                    b.Property<string>("AdminPwd")
                        .IsRequired();

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.HasKey("Id");

                    b.ToTable("HW_Admin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdminName = "Admin",
                            AdminPwd = "Admin123456",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 163, DateTimeKind.Local).AddTicks(5354),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 165, DateTimeKind.Local).AddTicks(1048)
                        },
                        new
                        {
                            Id = 2,
                            AdminName = "Mr.Fang",
                            AdminPwd = "Fh2269...",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 165, DateTimeKind.Local).AddTicks(2751),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 165, DateTimeKind.Local).AddTicks(2754)
                        });
                });

            modelBuilder.Entity("HW.Host.API.Model.DefaultEntity.HW_Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.Property<string>("UserPwd")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("HW_Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 165, DateTimeKind.Local).AddTicks(7241),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 165, DateTimeKind.Local).AddTicks(7246),
                            UserName = "Admin",
                            UserPwd = "Admin123456"
                        },
                        new
                        {
                            Id = 2,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(1518),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(1522),
                            UserName = "Mr.Fang",
                            UserPwd = "Fh2269..."
                        });
                });

            modelBuilder.Entity("HW.Host.API.Model.ModelEntity.HW_BackGroundImageInfo", b =>
                {
                    b.Property<int>("BGId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BGUrl");

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.HasKey("BGId");

                    b.ToTable("HW_BackGroundImageInfo");

                    b.HasData(
                        new
                        {
                            BGId = 1,
                            BGUrl = "/assets/images/backGround/bg1.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(6007),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(6010)
                        },
                        new
                        {
                            BGId = 2,
                            BGUrl = "/assets/images/backGround/bg2.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7399),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7401)
                        },
                        new
                        {
                            BGId = 3,
                            BGUrl = "/assets/images/backGround/bg3.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7436),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7437)
                        },
                        new
                        {
                            BGId = 4,
                            BGUrl = "/assets/images/backGround/bg4.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7452),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7453)
                        },
                        new
                        {
                            BGId = 5,
                            BGUrl = "/assets/images/backGround/bg5.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7464),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7465)
                        },
                        new
                        {
                            BGId = 6,
                            BGUrl = "/assets/images/backGround/bg6.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7479),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7479)
                        },
                        new
                        {
                            BGId = 7,
                            BGUrl = "/assets/images/backGround/bg7.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7490),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7491)
                        },
                        new
                        {
                            BGId = 8,
                            BGUrl = "/assets/images/backGround/bg8.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7502),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7503)
                        },
                        new
                        {
                            BGId = 9,
                            BGUrl = "/assets/images/backGround/bg9.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7517),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7517)
                        },
                        new
                        {
                            BGId = 10,
                            BGUrl = "/assets/images/backGround/bg10.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7529),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7530)
                        },
                        new
                        {
                            BGId = 11,
                            BGUrl = "/assets/images/backGround/bg11.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7542),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7542)
                        },
                        new
                        {
                            BGId = 12,
                            BGUrl = "/assets/images/backGround/bg12.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7553),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7554)
                        },
                        new
                        {
                            BGId = 13,
                            BGUrl = "/assets/images/backGround/bg13.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7565),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7566)
                        },
                        new
                        {
                            BGId = 14,
                            BGUrl = "/assets/images/backGround/bg14.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7577),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7577)
                        },
                        new
                        {
                            BGId = 15,
                            BGUrl = "/assets/images/backGround/bg15.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7806),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7806)
                        },
                        new
                        {
                            BGId = 16,
                            BGUrl = "/assets/images/backGround/bg16.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7822),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7823)
                        },
                        new
                        {
                            BGId = 17,
                            BGUrl = "/assets/images/backGround/bg17.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7835),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7835)
                        },
                        new
                        {
                            BGId = 18,
                            BGUrl = "/assets/images/backGround/bg18.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7848),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7848)
                        },
                        new
                        {
                            BGId = 19,
                            BGUrl = "/assets/images/backGround/bg19.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7860),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7860)
                        },
                        new
                        {
                            BGId = 20,
                            BGUrl = "/assets/images/backGround/bg20.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7872),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7873)
                        },
                        new
                        {
                            BGId = 21,
                            BGUrl = "/assets/images/backGround/bg21.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7884),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7884)
                        },
                        new
                        {
                            BGId = 22,
                            BGUrl = "/assets/images/backGround/bg22.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7897),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7897)
                        },
                        new
                        {
                            BGId = 23,
                            BGUrl = "/assets/images/backGround/bg23.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7909),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7909)
                        },
                        new
                        {
                            BGId = 24,
                            BGUrl = "/assets/images/backGround/bg24.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7921),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7922)
                        },
                        new
                        {
                            BGId = 25,
                            BGUrl = "/assets/images/backGround/bg25.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7933),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7934)
                        },
                        new
                        {
                            BGId = 26,
                            BGUrl = "/assets/images/backGround/bg26.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7946),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7947)
                        },
                        new
                        {
                            BGId = 27,
                            BGUrl = "/assets/images/backGround/bg27.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7958),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7958)
                        },
                        new
                        {
                            BGId = 28,
                            BGUrl = "/assets/images/backGround/bg28.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7970),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7970)
                        },
                        new
                        {
                            BGId = 29,
                            BGUrl = "/assets/images/backGround/bg29.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7983),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(7984)
                        },
                        new
                        {
                            BGId = 30,
                            BGUrl = "/assets/images/backGround/bg30.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8115),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8115)
                        },
                        new
                        {
                            BGId = 31,
                            BGUrl = "/assets/images/backGround/bg31.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8129),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8130)
                        },
                        new
                        {
                            BGId = 32,
                            BGUrl = "/assets/images/backGround/bg32.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8142),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8142)
                        },
                        new
                        {
                            BGId = 33,
                            BGUrl = "/assets/images/backGround/bg33.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8153),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8154)
                        },
                        new
                        {
                            BGId = 34,
                            BGUrl = "/assets/images/backGround/bg34.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8166),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8167)
                        },
                        new
                        {
                            BGId = 35,
                            BGUrl = "/assets/images/backGround/bg35.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8178),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8178)
                        },
                        new
                        {
                            BGId = 36,
                            BGUrl = "/assets/images/backGround/bg36.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8189),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8190)
                        },
                        new
                        {
                            BGId = 37,
                            BGUrl = "/assets/images/backGround/bg37.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8201),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8201)
                        },
                        new
                        {
                            BGId = 38,
                            BGUrl = "/assets/images/backGround/bg38.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8212),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8212)
                        },
                        new
                        {
                            BGId = 39,
                            BGUrl = "/assets/images/backGround/bg39.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8223),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8224)
                        },
                        new
                        {
                            BGId = 40,
                            BGUrl = "/assets/images/backGround/bg40.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8234),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8235)
                        },
                        new
                        {
                            BGId = 41,
                            BGUrl = "/assets/images/backGround/bg41.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8246),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8247)
                        },
                        new
                        {
                            BGId = 42,
                            BGUrl = "/assets/images/backGround/bg42.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8258),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8258)
                        },
                        new
                        {
                            BGId = 43,
                            BGUrl = "/assets/images/backGround/bg43.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8269),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8269)
                        },
                        new
                        {
                            BGId = 44,
                            BGUrl = "/assets/images/backGround/bg44.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8308),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8309)
                        },
                        new
                        {
                            BGId = 45,
                            BGUrl = "/assets/images/backGround/bg45.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8320),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8321)
                        },
                        new
                        {
                            BGId = 46,
                            BGUrl = "/assets/images/backGround/bg46.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8332),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8332)
                        },
                        new
                        {
                            BGId = 47,
                            BGUrl = "/assets/images/backGround/bg47.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8343),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8344)
                        },
                        new
                        {
                            BGId = 48,
                            BGUrl = "/assets/images/backGround/bg48.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8354),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8355)
                        },
                        new
                        {
                            BGId = 49,
                            BGUrl = "/assets/images/backGround/bg49.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8366),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8366)
                        },
                        new
                        {
                            BGId = 50,
                            BGUrl = "/assets/images/backGround/bg50.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8377),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8377)
                        },
                        new
                        {
                            BGId = 51,
                            BGUrl = "/assets/images/backGround/bg51.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8388),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8388)
                        },
                        new
                        {
                            BGId = 52,
                            BGUrl = "/assets/images/backGround/bg52.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8399),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8400)
                        },
                        new
                        {
                            BGId = 53,
                            BGUrl = "/assets/images/backGround/bg53.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8413),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8414)
                        },
                        new
                        {
                            BGId = 54,
                            BGUrl = "/assets/images/backGround/bg54.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8424),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8425)
                        },
                        new
                        {
                            BGId = 55,
                            BGUrl = "/assets/images/backGround/bg55.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8436),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8436)
                        },
                        new
                        {
                            BGId = 56,
                            BGUrl = "/assets/images/backGround/bg56.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8447),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8448)
                        },
                        new
                        {
                            BGId = 57,
                            BGUrl = "/assets/images/backGround/bg57.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8458),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8459)
                        },
                        new
                        {
                            BGId = 58,
                            BGUrl = "/assets/images/backGround/bg58.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8469),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8471)
                        },
                        new
                        {
                            BGId = 59,
                            BGUrl = "/assets/images/backGround/bg59.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8482),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8482)
                        },
                        new
                        {
                            BGId = 60,
                            BGUrl = "/assets/images/backGround/bg60.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8522),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8522)
                        },
                        new
                        {
                            BGId = 61,
                            BGUrl = "/assets/images/backGround/bg61.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8534),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8534)
                        },
                        new
                        {
                            BGId = 62,
                            BGUrl = "/assets/images/backGround/bg62.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8545),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8545)
                        },
                        new
                        {
                            BGId = 63,
                            BGUrl = "/assets/images/backGround/bg63.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8556),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8556)
                        },
                        new
                        {
                            BGId = 64,
                            BGUrl = "/assets/images/backGround/bg64.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8567),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8568)
                        },
                        new
                        {
                            BGId = 65,
                            BGUrl = "/assets/images/backGround/bg65.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8578),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8579)
                        },
                        new
                        {
                            BGId = 66,
                            BGUrl = "/assets/images/backGround/bg66.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8590),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8591)
                        },
                        new
                        {
                            BGId = 67,
                            BGUrl = "/assets/images/backGround/bg67.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8602),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8602)
                        },
                        new
                        {
                            BGId = 68,
                            BGUrl = "/assets/images/backGround/bg68.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8613),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8613)
                        },
                        new
                        {
                            BGId = 69,
                            BGUrl = "/assets/images/backGround/bg69.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8624),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8624)
                        },
                        new
                        {
                            BGId = 70,
                            BGUrl = "/assets/images/backGround/bg70.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8635),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8636)
                        },
                        new
                        {
                            BGId = 71,
                            BGUrl = "/assets/images/backGround/bg71.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8646),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8647)
                        },
                        new
                        {
                            BGId = 72,
                            BGUrl = "/assets/images/backGround/bg72.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8675),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8676)
                        },
                        new
                        {
                            BGId = 73,
                            BGUrl = "/assets/images/backGround/bg73.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8716),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8716)
                        },
                        new
                        {
                            BGId = 74,
                            BGUrl = "/assets/images/backGround/bg74.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8727),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8728)
                        },
                        new
                        {
                            BGId = 75,
                            BGUrl = "/assets/images/backGround/bg75.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8738),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8739)
                        },
                        new
                        {
                            BGId = 76,
                            BGUrl = "/assets/images/backGround/bg76.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8749),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8750)
                        },
                        new
                        {
                            BGId = 77,
                            BGUrl = "/assets/images/backGround/bg77.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8760),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8761)
                        },
                        new
                        {
                            BGId = 78,
                            BGUrl = "/assets/images/backGround/bg78.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8772),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8772)
                        },
                        new
                        {
                            BGId = 79,
                            BGUrl = "/assets/images/backGround/bg79.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8783),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8783)
                        },
                        new
                        {
                            BGId = 80,
                            BGUrl = "/assets/images/backGround/bg80.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8794),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8794)
                        },
                        new
                        {
                            BGId = 81,
                            BGUrl = "/assets/images/backGround/bg81.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8805),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8806)
                        },
                        new
                        {
                            BGId = 82,
                            BGUrl = "/assets/images/backGround/bg82.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8816),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8817)
                        },
                        new
                        {
                            BGId = 83,
                            BGUrl = "/assets/images/backGround/bg83.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8827),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8828)
                        },
                        new
                        {
                            BGId = 84,
                            BGUrl = "/assets/images/backGround/bg84.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8838),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8839)
                        },
                        new
                        {
                            BGId = 85,
                            BGUrl = "/assets/images/backGround/bg85.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8850),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8850)
                        },
                        new
                        {
                            BGId = 86,
                            BGUrl = "/assets/images/backGround/bg86.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8860),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8861)
                        },
                        new
                        {
                            BGId = 87,
                            BGUrl = "/assets/images/backGround/bg87.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8872),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(8872)
                        },
                        new
                        {
                            BGId = 88,
                            BGUrl = "/assets/images/backGround/bg88.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(9092),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(9093)
                        },
                        new
                        {
                            BGId = 89,
                            BGUrl = "/assets/images/backGround/bg89.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(9107),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(9108)
                        },
                        new
                        {
                            BGId = 90,
                            BGUrl = "/assets/images/backGround/bg90.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(9119),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(9120)
                        },
                        new
                        {
                            BGId = 91,
                            BGUrl = "/assets/images/backGround/bg91.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(9132),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(9132)
                        },
                        new
                        {
                            BGId = 92,
                            BGUrl = "/assets/images/backGround/bg92.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(9143),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(9144)
                        },
                        new
                        {
                            BGId = 93,
                            BGUrl = "/assets/images/backGround/bg93.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(9155),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(9155)
                        },
                        new
                        {
                            BGId = 94,
                            BGUrl = "/assets/images/backGround/bg94.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(9166),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(9167)
                        },
                        new
                        {
                            BGId = 95,
                            BGUrl = "/assets/images/backGround/bg95.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(9178),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(9179)
                        },
                        new
                        {
                            BGId = 96,
                            BGUrl = "/assets/images/backGround/bg96.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(9191),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(9191)
                        },
                        new
                        {
                            BGId = 97,
                            BGUrl = "/assets/images/backGround/bg97.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(9202),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(9203)
                        },
                        new
                        {
                            BGId = 98,
                            BGUrl = "/assets/images/backGround/bg98.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(9214),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(9215)
                        },
                        new
                        {
                            BGId = 99,
                            BGUrl = "/assets/images/backGround/bg99.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(9226),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(9227)
                        },
                        new
                        {
                            BGId = 100,
                            BGUrl = "/assets/images/backGround/bg100.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(9238),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(9239)
                        });
                });

            modelBuilder.Entity("HW.Host.API.Model.ModelEntity.HW_CopywritingInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.HasKey("Id");

                    b.ToTable("HW_CopywritingInfo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "当你的能力还撑不起你的野心的时，你就需要静下心来 好好学习。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(2700),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(2702)
                        },
                        new
                        {
                            Id = 2,
                            Content = "脏的人多了，干净反倒成了一种错。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(4676),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(4680)
                        },
                        new
                        {
                            Id = 3,
                            Content = "你羡慕的生活都是你没熬过的苦。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(4689),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(4690)
                        },
                        new
                        {
                            Id = 4,
                            Content = "所谓天才，只不过是把别人喝咖啡的功夫都用在了工作上了。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(4691),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(4692)
                        },
                        new
                        {
                            Id = 5,
                            Content = "生活便是寻求新的知识。——门捷列夫",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(4693),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(4694)
                        },
                        new
                        {
                            Id = 6,
                            Content = "如果你浪费了自己的年龄，那是挺可悲的。因为你的青春只能持续一点儿时间——很短的一点儿时间。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(4695),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(4696)
                        },
                        new
                        {
                            Id = 7,
                            Content = "世界上一成不变的东西，只有“任何事物都是在不断变化的”这条真理。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(4697),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 11, 30, 16, 49, 52, 166, DateTimeKind.Local).AddTicks(4698)
                        });
                });

            modelBuilder.Entity("HW.Host.API.Model.ModelEntity.HW_EmailHistoryInfo", b =>
                {
                    b.Property<int>("EHID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<string>("EmailBody")
                        .IsRequired();

                    b.Property<string>("EmailCode");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.Property<string>("RecipientId")
                        .IsRequired();

                    b.HasKey("EHID");

                    b.ToTable("HW_EmailHistoryInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
