// <auto-generated />
using System;
using HW.Host.API.Infrastructure.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HW.Host.API.Infrastructure.Migrations
{
    [DbContext(typeof(HWHostDbContext))]
    [Migration("20201201031438_Add_Table_HW_PhoneReceiveInfo")]
    partial class Add_Table_HW_PhoneReceiveInfo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HW.Host.API.Model.DefaultEntity.HW_Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdminName")
                        .IsRequired();

                    b.Property<string>("AdminPwd")
                        .IsRequired();

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.HasKey("Id");

                    b.ToTable("HW_Admin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdminName = "Admin",
                            AdminPwd = "Admin123456",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 598, DateTimeKind.Local).AddTicks(3239),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 599, DateTimeKind.Local).AddTicks(6380)
                        },
                        new
                        {
                            Id = 2,
                            AdminName = "Mr.Fang",
                            AdminPwd = "Fh2269...",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 599, DateTimeKind.Local).AddTicks(8075),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 599, DateTimeKind.Local).AddTicks(8078)
                        });
                });

            modelBuilder.Entity("HW.Host.API.Model.DefaultEntity.HW_Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.Property<string>("UserPwd")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("HW_Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(735),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(738),
                            UserName = "Admin",
                            UserPwd = "Admin123456"
                        },
                        new
                        {
                            Id = 2,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(2290),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(2292),
                            UserName = "Mr.Fang",
                            UserPwd = "Fh2269..."
                        });
                });

            modelBuilder.Entity("HW.Host.API.Model.ModelEntity.HW_BackGroundImageInfo", b =>
                {
                    b.Property<int>("BGId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BGUrl");

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.HasKey("BGId");

                    b.ToTable("HW_BackGroundImageInfo");

                    b.HasData(
                        new
                        {
                            BGId = 1,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg1.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(5106),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(5109)
                        },
                        new
                        {
                            BGId = 2,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg2.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6411),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6413)
                        },
                        new
                        {
                            BGId = 3,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg3.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6445),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6446)
                        },
                        new
                        {
                            BGId = 4,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg4.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6510),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6511)
                        },
                        new
                        {
                            BGId = 5,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg5.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6524),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6524)
                        },
                        new
                        {
                            BGId = 6,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg6.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6539),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6539)
                        },
                        new
                        {
                            BGId = 7,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg7.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6550),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6550)
                        },
                        new
                        {
                            BGId = 8,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg8.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6561),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6562)
                        },
                        new
                        {
                            BGId = 9,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg9.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6572),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6573)
                        },
                        new
                        {
                            BGId = 10,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg10.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6584),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6585)
                        },
                        new
                        {
                            BGId = 11,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg11.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6597),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6597)
                        },
                        new
                        {
                            BGId = 12,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg12.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6608),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6608)
                        },
                        new
                        {
                            BGId = 13,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg13.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6619),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6619)
                        },
                        new
                        {
                            BGId = 14,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg14.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6630),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6631)
                        },
                        new
                        {
                            BGId = 15,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg15.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6641),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6642)
                        },
                        new
                        {
                            BGId = 16,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg16.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6652),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6653)
                        },
                        new
                        {
                            BGId = 17,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg17.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6663),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6664)
                        },
                        new
                        {
                            BGId = 18,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg18.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6709),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6709)
                        },
                        new
                        {
                            BGId = 19,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg19.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6720),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6720)
                        },
                        new
                        {
                            BGId = 20,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg20.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6731),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6731)
                        },
                        new
                        {
                            BGId = 21,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg21.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6742),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6742)
                        },
                        new
                        {
                            BGId = 22,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg22.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6753),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6753)
                        },
                        new
                        {
                            BGId = 23,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg23.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6764),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6764)
                        },
                        new
                        {
                            BGId = 24,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg24.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6775),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6775)
                        },
                        new
                        {
                            BGId = 25,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg25.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6786),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6786)
                        },
                        new
                        {
                            BGId = 26,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg26.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6797),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6797)
                        },
                        new
                        {
                            BGId = 27,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg27.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6808),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6808)
                        },
                        new
                        {
                            BGId = 28,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg28.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6819),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6819)
                        },
                        new
                        {
                            BGId = 29,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg29.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6829),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6830)
                        },
                        new
                        {
                            BGId = 30,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg30.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6840),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6841)
                        },
                        new
                        {
                            BGId = 31,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg31.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6915),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6916)
                        },
                        new
                        {
                            BGId = 32,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg32.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6928),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6928)
                        },
                        new
                        {
                            BGId = 33,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg33.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6939),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6940)
                        },
                        new
                        {
                            BGId = 34,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg34.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6951),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6952)
                        },
                        new
                        {
                            BGId = 35,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg35.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6962),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6963)
                        },
                        new
                        {
                            BGId = 36,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg36.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6973),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6974)
                        },
                        new
                        {
                            BGId = 37,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg37.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6984),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6985)
                        },
                        new
                        {
                            BGId = 38,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg38.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6996),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(6996)
                        },
                        new
                        {
                            BGId = 39,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg39.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7007),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7007)
                        },
                        new
                        {
                            BGId = 40,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg40.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7018),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7018)
                        },
                        new
                        {
                            BGId = 41,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg41.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7029),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7030)
                        },
                        new
                        {
                            BGId = 42,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg42.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7040),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7041)
                        },
                        new
                        {
                            BGId = 43,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg43.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7051),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7052)
                        },
                        new
                        {
                            BGId = 44,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg44.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7102),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7103)
                        },
                        new
                        {
                            BGId = 45,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg45.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7115),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7116)
                        },
                        new
                        {
                            BGId = 46,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg46.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7126),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7127)
                        },
                        new
                        {
                            BGId = 47,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg47.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7137),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7138)
                        },
                        new
                        {
                            BGId = 48,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg48.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7148),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7149)
                        },
                        new
                        {
                            BGId = 49,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg49.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7159),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7160)
                        },
                        new
                        {
                            BGId = 50,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg50.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7170),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7170)
                        },
                        new
                        {
                            BGId = 51,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg51.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7181),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7181)
                        },
                        new
                        {
                            BGId = 52,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg52.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7192),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7192)
                        },
                        new
                        {
                            BGId = 53,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg53.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7203),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7203)
                        },
                        new
                        {
                            BGId = 54,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg54.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7213),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7214)
                        },
                        new
                        {
                            BGId = 55,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg55.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7225),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7225)
                        },
                        new
                        {
                            BGId = 56,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg56.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7235),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7236)
                        },
                        new
                        {
                            BGId = 57,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg57.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7246),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7247)
                        },
                        new
                        {
                            BGId = 58,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg58.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7291),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7291)
                        },
                        new
                        {
                            BGId = 59,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg59.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7303),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7303)
                        },
                        new
                        {
                            BGId = 60,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg60.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7314),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7314)
                        },
                        new
                        {
                            BGId = 61,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg61.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7325),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7325)
                        },
                        new
                        {
                            BGId = 62,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg62.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7336),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7336)
                        },
                        new
                        {
                            BGId = 63,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg63.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7346),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7347)
                        },
                        new
                        {
                            BGId = 64,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg64.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7358),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7358)
                        },
                        new
                        {
                            BGId = 65,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg65.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7368),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7369)
                        },
                        new
                        {
                            BGId = 66,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg66.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7380),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7381)
                        },
                        new
                        {
                            BGId = 67,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg67.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7391),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7392)
                        },
                        new
                        {
                            BGId = 68,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg68.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7424),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7425)
                        },
                        new
                        {
                            BGId = 69,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg69.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7435),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7436)
                        },
                        new
                        {
                            BGId = 70,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg70.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7446),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7447)
                        },
                        new
                        {
                            BGId = 71,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg71.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7489),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7490)
                        },
                        new
                        {
                            BGId = 72,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg72.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7500),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7501)
                        },
                        new
                        {
                            BGId = 73,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg73.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7511),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7512)
                        },
                        new
                        {
                            BGId = 74,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg74.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7522),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7523)
                        },
                        new
                        {
                            BGId = 75,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg75.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7533),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7533)
                        },
                        new
                        {
                            BGId = 76,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg76.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7543),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7544)
                        },
                        new
                        {
                            BGId = 77,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg77.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7554),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7555)
                        },
                        new
                        {
                            BGId = 78,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg78.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7566),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7566)
                        },
                        new
                        {
                            BGId = 79,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg79.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7577),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7577)
                        },
                        new
                        {
                            BGId = 80,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg80.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7588),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7588)
                        },
                        new
                        {
                            BGId = 81,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg81.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7599),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7599)
                        },
                        new
                        {
                            BGId = 82,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg82.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7609),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7610)
                        },
                        new
                        {
                            BGId = 83,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg83.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7620),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7621)
                        },
                        new
                        {
                            BGId = 84,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg84.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7631),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7632)
                        },
                        new
                        {
                            BGId = 85,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg85.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7679),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7680)
                        },
                        new
                        {
                            BGId = 86,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg86.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7690),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7691)
                        },
                        new
                        {
                            BGId = 87,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg87.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7701),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7702)
                        },
                        new
                        {
                            BGId = 88,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg88.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7712),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7713)
                        },
                        new
                        {
                            BGId = 89,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg89.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7723),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7723)
                        },
                        new
                        {
                            BGId = 90,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg90.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7734),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7734)
                        },
                        new
                        {
                            BGId = 91,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg91.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7744),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7745)
                        },
                        new
                        {
                            BGId = 92,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg92.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7756),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7757)
                        },
                        new
                        {
                            BGId = 93,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg93.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7767),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7767)
                        },
                        new
                        {
                            BGId = 94,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg94.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7777),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7778)
                        },
                        new
                        {
                            BGId = 95,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg95.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7788),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7789)
                        },
                        new
                        {
                            BGId = 96,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg96.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7799),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7800)
                        },
                        new
                        {
                            BGId = 97,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg97.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7810),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7810)
                        },
                        new
                        {
                            BGId = 98,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg98.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7821),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7821)
                        },
                        new
                        {
                            BGId = 99,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg99.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7868),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7868)
                        },
                        new
                        {
                            BGId = 100,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg100.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7905),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(7906)
                        });
                });

            modelBuilder.Entity("HW.Host.API.Model.ModelEntity.HW_CopywritingInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.HasKey("Id");

                    b.ToTable("HW_CopywritingInfo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "当你的能力还撑不起你的野心的时，你就需要静下心来 好好学习。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(3340),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(3342)
                        },
                        new
                        {
                            Id = 2,
                            Content = "脏的人多了，干净反倒成了一种错。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(4197),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(4199)
                        },
                        new
                        {
                            Id = 3,
                            Content = "你羡慕的生活都是你没熬过的苦。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(4208),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(4208)
                        },
                        new
                        {
                            Id = 4,
                            Content = "所谓天才，只不过是把别人喝咖啡的功夫都用在了工作上了。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(4210),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(4211)
                        },
                        new
                        {
                            Id = 5,
                            Content = "生活便是寻求新的知识。——门捷列夫",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(4212),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(4213)
                        },
                        new
                        {
                            Id = 6,
                            Content = "如果你浪费了自己的年龄，那是挺可悲的。因为你的青春只能持续一点儿时间——很短的一点儿时间。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(4214),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(4215)
                        },
                        new
                        {
                            Id = 7,
                            Content = "世界上一成不变的东西，只有“任何事物都是在不断变化的”这条真理。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(4216),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 1, 11, 14, 38, 600, DateTimeKind.Local).AddTicks(4217)
                        });
                });

            modelBuilder.Entity("HW.Host.API.Model.ModelEntity.HW_EmailHistoryInfo", b =>
                {
                    b.Property<int>("EHID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<string>("EmailBody")
                        .IsRequired();

                    b.Property<string>("EmailCode");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.Property<string>("RecipientId")
                        .IsRequired();

                    b.HasKey("EHID");

                    b.ToTable("HW_EmailHistoryInfo");
                });

            modelBuilder.Entity("HW.Host.API.Model.ModelEntity.HW_PhoneModelInfo", b =>
                {
                    b.Property<int>("PhoneID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PhoneCode")
                        .IsRequired();

                    b.Property<string>("PhoneColour")
                        .IsRequired();

                    b.Property<string>("PhoneFineness")
                        .IsRequired();

                    b.Property<int>("PhoneIsReturn");

                    b.Property<DateTime>("PhoneLeaseTime");

                    b.Property<string>("PhoneName")
                        .IsRequired();

                    b.Property<int>("PhonePrice");

                    b.Property<string>("PhoneRAM")
                        .IsRequired();

                    b.Property<string>("PhoneRemarks");

                    b.Property<string>("PhoneReturnRemarks");

                    b.Property<DateTime>("PhoneReturnTime");

                    b.HasKey("PhoneID");

                    b.ToTable("HW_PhoneModelInfo");

                    b.HasData(
                        new
                        {
                            PhoneID = 1,
                            PhoneCode = "862754045574919",
                            PhoneColour = "红",
                            PhoneFineness = "95",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "VIVO X23",
                            PhonePrice = 1000,
                            PhoneRAM = "8+128",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PhoneID = 2,
                            PhoneCode = "860450040094555",
                            PhoneColour = "黑",
                            PhoneFineness = "靓",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "华为畅享Z 5G",
                            PhonePrice = 1250,
                            PhoneRAM = "6+64",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PhoneID = 3,
                            PhoneCode = "861189053704549",
                            PhoneColour = "蓝",
                            PhoneFineness = "靓",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "华为畅享20Pro 5G",
                            PhonePrice = 1600,
                            PhoneRAM = "6+128",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PhoneID = 4,
                            PhoneCode = "866216030724606",
                            PhoneColour = "粉",
                            PhoneFineness = "靓",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "华为Mate10 Pro",
                            PhonePrice = 1000,
                            PhoneRAM = "6+64",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PhoneID = 5,
                            PhoneCode = "868034039428685",
                            PhoneColour = "黑",
                            PhoneFineness = "9",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "华为Mate10 Pro",
                            PhonePrice = 950,
                            PhoneRAM = "6+128",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PhoneID = 6,
                            PhoneCode = "865043042963151",
                            PhoneColour = "蓝",
                            PhoneFineness = "9",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "华为Mate20",
                            PhonePrice = 1200,
                            PhoneRAM = "6+64",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PhoneID = 7,
                            PhoneCode = "868577030922627",
                            PhoneColour = "黑",
                            PhoneFineness = "95",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "华为P20Pro",
                            PhonePrice = 1050,
                            PhoneRAM = "6+64",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PhoneID = 8,
                            PhoneCode = "864928040295179",
                            PhoneColour = "蓝",
                            PhoneFineness = "95",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "华为Nova5i",
                            PhonePrice = 1200,
                            PhoneRAM = "8+128",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PhoneID = 9,
                            PhoneCode = "862474042226765",
                            PhoneColour = "黑",
                            PhoneFineness = "靓",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "华为P30",
                            PhonePrice = 1800,
                            PhoneRAM = "8+64",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PhoneID = 10,
                            PhoneCode = "860133058133412",
                            PhoneColour = "黑",
                            PhoneFineness = "靓",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "华为Nova7SE5G",
                            PhonePrice = 2100,
                            PhoneRAM = "8+128",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PhoneID = 11,
                            PhoneCode = "861594045284619",
                            PhoneColour = "粉",
                            PhoneFineness = "靓",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "华为P20",
                            PhonePrice = 1100,
                            PhoneRAM = "6+128",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PhoneID = 12,
                            PhoneCode = "99001343870346",
                            PhoneColour = "黑",
                            PhoneFineness = "95",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "小米9",
                            PhonePrice = 1500,
                            PhoneRAM = "8+128",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PhoneID = 13,
                            PhoneCode = "99001332374714",
                            PhoneColour = "蓝",
                            PhoneFineness = "9",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "小米9",
                            PhonePrice = 1150,
                            PhoneRAM = "6+128",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PhoneID = 14,
                            PhoneCode = "99001583306158",
                            PhoneColour = "白",
                            PhoneFineness = "靓",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "小米10青春版",
                            PhonePrice = 1700,
                            PhoneRAM = "8+128",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PhoneID = 15,
                            PhoneCode = "99001302146726",
                            PhoneColour = "白",
                            PhoneFineness = "靓",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "红米K20Pro",
                            PhonePrice = 1450,
                            PhoneRAM = "8+128",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HW.Host.API.Model.ModelEntity.HW_PhoneReceiveInfo", b =>
                {
                    b.Property<int>("ReceiveID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ReceiveIsReturn");

                    b.Property<int>("ReceivePhoneModelID");

                    b.Property<string>("ReceiveRemarks");

                    b.Property<DateTime>("ReceiveReturnTime");

                    b.Property<DateTime>("ReceiveTime");

                    b.Property<int>("ReceiveUserID");

                    b.Property<string>("ReturnRemarks");

                    b.HasKey("ReceiveID");

                    b.HasIndex("ReceivePhoneModelID");

                    b.HasIndex("ReceiveUserID");

                    b.ToTable("HW_PhoneReceiveInfo");

                    b.HasData(
                        new
                        {
                            ReceiveID = 1,
                            ReceiveIsReturn = 0,
                            ReceivePhoneModelID = 1,
                            ReceiveRemarks = "Hua.MrF测试~",
                            ReceiveReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiveTime = new DateTime(2020, 12, 1, 11, 14, 38, 601, DateTimeKind.Local).AddTicks(6270),
                            ReceiveUserID = 2
                        },
                        new
                        {
                            ReceiveID = 2,
                            ReceiveIsReturn = 0,
                            ReceivePhoneModelID = 2,
                            ReceiveRemarks = "Hua.MrF测试~",
                            ReceiveReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiveTime = new DateTime(2020, 12, 1, 11, 14, 38, 601, DateTimeKind.Local).AddTicks(7954),
                            ReceiveUserID = 2
                        },
                        new
                        {
                            ReceiveID = 3,
                            ReceiveIsReturn = 0,
                            ReceivePhoneModelID = 3,
                            ReceiveRemarks = "Hua.MrF测试~",
                            ReceiveReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiveTime = new DateTime(2020, 12, 1, 11, 14, 38, 601, DateTimeKind.Local).AddTicks(7969),
                            ReceiveUserID = 2
                        });
                });

            modelBuilder.Entity("HW.Host.API.Model.ModelEntity.HW_PhoneReceiveInfo", b =>
                {
                    b.HasOne("HW.Host.API.Model.ModelEntity.HW_PhoneModelInfo", "HW_PhoneModelInfo")
                        .WithMany()
                        .HasForeignKey("ReceivePhoneModelID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HW.Host.API.Model.DefaultEntity.HW_Users", "HW_Users")
                        .WithMany()
                        .HasForeignKey("ReceiveUserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
