// <auto-generated />
using System;
using HW.Host.API.Infrastructure.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HW.Host.API.Infrastructure.Migrations
{
    [DbContext(typeof(HWHostDbContext))]
    [Migration("20201207062502_Update_Table_Id_Other")]
    partial class Update_Table_Id_Other
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HW.Host.API.Model.DefaultEntity.HW_Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdminName")
                        .IsRequired();

                    b.Property<string>("AdminPwd")
                        .IsRequired();

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.HasKey("Id");

                    b.ToTable("HW_Admin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdminName = "Admin",
                            AdminPwd = "Admin123456",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 206, DateTimeKind.Local).AddTicks(8685),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(1041)
                        },
                        new
                        {
                            Id = 2,
                            AdminName = "Mr.Fang",
                            AdminPwd = "Fh2269...",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(2188),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(2192)
                        });
                });

            modelBuilder.Entity("HW.Host.API.Model.DefaultEntity.HW_Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.Property<string>("UserPwd")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("HW_Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(4570),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(4573),
                            UserName = "Admin",
                            UserPwd = "Admin123456"
                        },
                        new
                        {
                            Id = 2,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(5545),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(5547),
                            UserName = "Mr.Fang",
                            UserPwd = "Fh2269..."
                        });
                });

            modelBuilder.Entity("HW.Host.API.Model.ModelEntity.HW_BackGroundImageInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BGUrl");

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.HasKey("Id");

                    b.ToTable("HW_BackGroundImageInfo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg1.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(7732),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(7734)
                        },
                        new
                        {
                            Id = 2,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg2.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8503),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8505)
                        },
                        new
                        {
                            Id = 3,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg3.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8533),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8534)
                        },
                        new
                        {
                            Id = 4,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg4.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8548),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8549)
                        },
                        new
                        {
                            Id = 5,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg5.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8561),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8561)
                        },
                        new
                        {
                            Id = 6,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg6.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8576),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8577)
                        },
                        new
                        {
                            Id = 7,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg7.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8590),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8591)
                        },
                        new
                        {
                            Id = 8,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg8.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8601),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8602)
                        },
                        new
                        {
                            Id = 9,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg9.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8612),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8613)
                        },
                        new
                        {
                            Id = 10,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg10.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8625),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8626)
                        },
                        new
                        {
                            Id = 11,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg11.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8637),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8638)
                        },
                        new
                        {
                            Id = 12,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg12.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8648),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8649)
                        },
                        new
                        {
                            Id = 13,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg13.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8725),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8726)
                        },
                        new
                        {
                            Id = 14,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg14.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8737),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8738)
                        },
                        new
                        {
                            Id = 15,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg15.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8748),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8749)
                        },
                        new
                        {
                            Id = 16,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg16.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8759),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8760)
                        },
                        new
                        {
                            Id = 17,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg17.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8771),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8771)
                        },
                        new
                        {
                            Id = 18,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg18.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8783),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8783)
                        },
                        new
                        {
                            Id = 19,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg19.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8794),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8795)
                        },
                        new
                        {
                            Id = 20,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg20.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8806),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8806)
                        },
                        new
                        {
                            Id = 21,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg21.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8817),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8817)
                        },
                        new
                        {
                            Id = 22,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg22.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8828),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8828)
                        },
                        new
                        {
                            Id = 23,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg23.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8839),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8840)
                        },
                        new
                        {
                            Id = 24,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg24.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8850),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8851)
                        },
                        new
                        {
                            Id = 25,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg25.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8861),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8862)
                        },
                        new
                        {
                            Id = 26,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg26.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8898),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8899)
                        },
                        new
                        {
                            Id = 27,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg27.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8910),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8910)
                        },
                        new
                        {
                            Id = 28,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg28.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8921),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8922)
                        },
                        new
                        {
                            Id = 29,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg29.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8932),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8933)
                        },
                        new
                        {
                            Id = 30,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg30.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8944),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8944)
                        },
                        new
                        {
                            Id = 31,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg31.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8954),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8955)
                        },
                        new
                        {
                            Id = 32,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg32.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8965),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8966)
                        },
                        new
                        {
                            Id = 33,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg33.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8977),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8977)
                        },
                        new
                        {
                            Id = 34,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg34.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8989),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(8989)
                        },
                        new
                        {
                            Id = 35,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg35.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9000),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9000)
                        },
                        new
                        {
                            Id = 36,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg36.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9011),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9011)
                        },
                        new
                        {
                            Id = 37,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg37.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9022),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9022)
                        },
                        new
                        {
                            Id = 38,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg38.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9033),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9033)
                        },
                        new
                        {
                            Id = 39,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg39.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9069),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9070)
                        },
                        new
                        {
                            Id = 40,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg40.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9081),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9082)
                        },
                        new
                        {
                            Id = 41,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg41.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9092),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9093)
                        },
                        new
                        {
                            Id = 42,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg42.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9103),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9104)
                        },
                        new
                        {
                            Id = 43,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg43.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9114),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9115)
                        },
                        new
                        {
                            Id = 44,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg44.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9125),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9126)
                        },
                        new
                        {
                            Id = 45,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg45.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9136),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9137)
                        },
                        new
                        {
                            Id = 46,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg46.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9147),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9148)
                        },
                        new
                        {
                            Id = 47,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg47.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9158),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9159)
                        },
                        new
                        {
                            Id = 48,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg48.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9169),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9170)
                        },
                        new
                        {
                            Id = 49,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg49.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9180),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9181)
                        },
                        new
                        {
                            Id = 50,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg50.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9192),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9192)
                        },
                        new
                        {
                            Id = 51,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg51.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9202),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9203)
                        },
                        new
                        {
                            Id = 52,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg52.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9213),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9214)
                        },
                        new
                        {
                            Id = 53,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg53.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9250),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9251)
                        },
                        new
                        {
                            Id = 54,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg54.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9262),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9263)
                        },
                        new
                        {
                            Id = 55,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg55.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9273),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9274)
                        },
                        new
                        {
                            Id = 56,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg56.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9284),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9285)
                        },
                        new
                        {
                            Id = 57,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg57.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9295),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9296)
                        },
                        new
                        {
                            Id = 58,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg58.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9306),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9307)
                        },
                        new
                        {
                            Id = 59,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg59.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9317),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9318)
                        },
                        new
                        {
                            Id = 60,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg60.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9328),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9329)
                        },
                        new
                        {
                            Id = 61,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg61.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9339),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9340)
                        },
                        new
                        {
                            Id = 62,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg62.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9350),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9351)
                        },
                        new
                        {
                            Id = 63,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg63.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9361),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9362)
                        },
                        new
                        {
                            Id = 64,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg64.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9373),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9373)
                        },
                        new
                        {
                            Id = 65,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg65.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9383),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9384)
                        },
                        new
                        {
                            Id = 66,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg66.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9422),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9423)
                        },
                        new
                        {
                            Id = 67,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg67.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9433),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9434)
                        },
                        new
                        {
                            Id = 68,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg68.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9457),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9458)
                        },
                        new
                        {
                            Id = 69,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg69.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9469),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9469)
                        },
                        new
                        {
                            Id = 70,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg70.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9480),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9480)
                        },
                        new
                        {
                            Id = 71,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg71.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9491),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9491)
                        },
                        new
                        {
                            Id = 72,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg72.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9502),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9502)
                        },
                        new
                        {
                            Id = 73,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg73.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9513),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9514)
                        },
                        new
                        {
                            Id = 74,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg74.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9524),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9525)
                        },
                        new
                        {
                            Id = 75,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg75.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9536),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9536)
                        },
                        new
                        {
                            Id = 76,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg76.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9547),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9547)
                        },
                        new
                        {
                            Id = 77,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg77.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9558),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9558)
                        },
                        new
                        {
                            Id = 78,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg78.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9569),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9569)
                        },
                        new
                        {
                            Id = 79,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg79.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9580),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9580)
                        },
                        new
                        {
                            Id = 80,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg80.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9618),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9619)
                        },
                        new
                        {
                            Id = 81,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg81.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9629),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9630)
                        },
                        new
                        {
                            Id = 82,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg82.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9640),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9641)
                        },
                        new
                        {
                            Id = 83,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg83.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9651),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9652)
                        },
                        new
                        {
                            Id = 84,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg84.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9662),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9663)
                        },
                        new
                        {
                            Id = 85,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg85.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9673),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9674)
                        },
                        new
                        {
                            Id = 86,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg86.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9684),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9685)
                        },
                        new
                        {
                            Id = 87,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg87.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9696),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9696)
                        },
                        new
                        {
                            Id = 88,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg88.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9706),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9707)
                        },
                        new
                        {
                            Id = 89,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg89.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9717),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9718)
                        },
                        new
                        {
                            Id = 90,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg90.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9729),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9729)
                        },
                        new
                        {
                            Id = 91,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg91.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9740),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9740)
                        },
                        new
                        {
                            Id = 92,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg92.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9751),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9751)
                        },
                        new
                        {
                            Id = 93,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg93.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9762),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9762)
                        },
                        new
                        {
                            Id = 94,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg94.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9799),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9800)
                        },
                        new
                        {
                            Id = 95,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg95.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9810),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9811)
                        },
                        new
                        {
                            Id = 96,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg96.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9821),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9822)
                        },
                        new
                        {
                            Id = 97,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg97.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9832),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9833)
                        },
                        new
                        {
                            Id = 98,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg98.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9843),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9844)
                        },
                        new
                        {
                            Id = 99,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg99.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9855),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9855)
                        },
                        new
                        {
                            Id = 100,
                            BGUrl = "http://192.168.6.88:8888/assets/images/backGround/bg100.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9888),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(9889)
                        });
                });

            modelBuilder.Entity("HW.Host.API.Model.ModelEntity.HW_CopywritingInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.HasKey("Id");

                    b.ToTable("HW_CopywritingInfo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "当你的能力还撑不起你的野心的时，你就需要静下心来 好好学习。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(6279),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(6281)
                        },
                        new
                        {
                            Id = 2,
                            Content = "脏的人多了，干净反倒成了一种错。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(6791),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(6793)
                        },
                        new
                        {
                            Id = 3,
                            Content = "你羡慕的生活都是你没熬过的苦。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(6801),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(6801)
                        },
                        new
                        {
                            Id = 4,
                            Content = "所谓天才，只不过是把别人喝咖啡的功夫都用在了工作上了。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(6802),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(6803)
                        },
                        new
                        {
                            Id = 5,
                            Content = "生活便是寻求新的知识。——门捷列夫",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(6803),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(6804)
                        },
                        new
                        {
                            Id = 6,
                            Content = "如果你浪费了自己的年龄，那是挺可悲的。因为你的青春只能持续一点儿时间——很短的一点儿时间。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(6805),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(6806)
                        },
                        new
                        {
                            Id = 7,
                            Content = "世界上一成不变的东西，只有“任何事物都是在不断变化的”这条真理。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(6807),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 208, DateTimeKind.Local).AddTicks(6807)
                        });
                });

            modelBuilder.Entity("HW.Host.API.Model.ModelEntity.HW_EmailHistoryInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<string>("EmailBody")
                        .IsRequired();

                    b.Property<string>("EmailCode");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.Property<string>("RecipientId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("HW_EmailHistoryInfo");
                });

            modelBuilder.Entity("HW.Host.API.Model.ModelEntity.HW_PhoneModelInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.Property<string>("PhoneCode")
                        .IsRequired();

                    b.Property<string>("PhoneColour")
                        .IsRequired();

                    b.Property<string>("PhoneFineness")
                        .IsRequired();

                    b.Property<int>("PhoneIsReturn");

                    b.Property<DateTime>("PhoneLeaseTime");

                    b.Property<string>("PhoneName")
                        .IsRequired();

                    b.Property<int>("PhonePrice");

                    b.Property<string>("PhoneRAM")
                        .IsRequired();

                    b.Property<string>("PhoneRemarks");

                    b.Property<string>("PhoneReturnRemarks");

                    b.Property<DateTime>("PhoneReturnTime");

                    b.HasKey("Id");

                    b.ToTable("HW_PhoneModelInfo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(368),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(370),
                            PhoneCode = "862754045574919",
                            PhoneColour = "红",
                            PhoneFineness = "95",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "VIVO X23",
                            PhonePrice = 1000,
                            PhoneRAM = "8+128",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(5399),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(5402),
                            PhoneCode = "860450040094555",
                            PhoneColour = "黑",
                            PhoneFineness = "靓",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "华为畅享Z 5G",
                            PhonePrice = 1250,
                            PhoneRAM = "6+64",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(5449),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(5450),
                            PhoneCode = "861189053704549",
                            PhoneColour = "蓝",
                            PhoneFineness = "靓",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "华为畅享20Pro 5G",
                            PhonePrice = 1600,
                            PhoneRAM = "6+128",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(5457),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(5458),
                            PhoneCode = "866216030724606",
                            PhoneColour = "粉",
                            PhoneFineness = "靓",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "华为Mate10 Pro",
                            PhonePrice = 1000,
                            PhoneRAM = "6+64",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(5464),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(5464),
                            PhoneCode = "868034039428685",
                            PhoneColour = "黑",
                            PhoneFineness = "9",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "华为Mate10 Pro",
                            PhonePrice = 950,
                            PhoneRAM = "6+128",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(5469),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(5470),
                            PhoneCode = "865043042963151",
                            PhoneColour = "蓝",
                            PhoneFineness = "9",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "华为Mate20",
                            PhonePrice = 1200,
                            PhoneRAM = "6+64",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(5475),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(5475),
                            PhoneCode = "868577030922627",
                            PhoneColour = "黑",
                            PhoneFineness = "95",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "华为P20Pro",
                            PhonePrice = 1050,
                            PhoneRAM = "6+64",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(5480),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(5481),
                            PhoneCode = "864928040295179",
                            PhoneColour = "蓝",
                            PhoneFineness = "95",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "华为Nova5i",
                            PhonePrice = 1200,
                            PhoneRAM = "8+128",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(5486),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(5486),
                            PhoneCode = "862474042226765",
                            PhoneColour = "黑",
                            PhoneFineness = "靓",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "华为P30",
                            PhonePrice = 1800,
                            PhoneRAM = "8+64",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(5491),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(5492),
                            PhoneCode = "860133058133412",
                            PhoneColour = "黑",
                            PhoneFineness = "靓",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "华为Nova7SE5G",
                            PhonePrice = 2100,
                            PhoneRAM = "8+128",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(5497),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(5497),
                            PhoneCode = "861594045284619",
                            PhoneColour = "粉",
                            PhoneFineness = "靓",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "华为P20",
                            PhonePrice = 1100,
                            PhoneRAM = "6+128",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(5503),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(5503),
                            PhoneCode = "99001343870346",
                            PhoneColour = "黑",
                            PhoneFineness = "95",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "小米9",
                            PhonePrice = 1500,
                            PhoneRAM = "8+128",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(5508),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(5509),
                            PhoneCode = "99001332374714",
                            PhoneColour = "蓝",
                            PhoneFineness = "9",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "小米9",
                            PhonePrice = 1150,
                            PhoneRAM = "6+128",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(5514),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(5514),
                            PhoneCode = "99001583306158",
                            PhoneColour = "白",
                            PhoneFineness = "靓",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "小米10青春版",
                            PhonePrice = 1700,
                            PhoneRAM = "8+128",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(5519),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(5520),
                            PhoneCode = "99001302146726",
                            PhoneColour = "白",
                            PhoneFineness = "靓",
                            PhoneIsReturn = 0,
                            PhoneLeaseTime = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneName = "红米K20Pro",
                            PhonePrice = 1450,
                            PhoneRAM = "8+128",
                            PhoneReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HW.Host.API.Model.ModelEntity.HW_PhoneReceiveInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.Property<int>("ReceiveIsReturn");

                    b.Property<int>("ReceivePhoneModelID");

                    b.Property<string>("ReceiveRemarks");

                    b.Property<DateTime>("ReceiveReturnTime");

                    b.Property<DateTime>("ReceiveTime");

                    b.Property<int>("ReceiveUserID");

                    b.Property<string>("ReturnRemarks");

                    b.HasKey("Id");

                    b.HasIndex("ReceivePhoneModelID");

                    b.HasIndex("ReceiveUserID");

                    b.ToTable("HW_PhoneReceiveInfo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(6486),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(6487),
                            ReceiveIsReturn = 0,
                            ReceivePhoneModelID = 1,
                            ReceiveRemarks = "Hua.MrF测试~",
                            ReceiveReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiveTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(6484),
                            ReceiveUserID = 2
                        },
                        new
                        {
                            Id = 2,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(7687),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(7688),
                            ReceiveIsReturn = 0,
                            ReceivePhoneModelID = 2,
                            ReceiveRemarks = "Hua.MrF测试~",
                            ReceiveReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiveTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(7685),
                            ReceiveUserID = 2
                        },
                        new
                        {
                            Id = 3,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(7740),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(7740),
                            ReceiveIsReturn = 0,
                            ReceivePhoneModelID = 3,
                            ReceiveRemarks = "Hua.MrF测试~",
                            ReceiveReturnTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiveTime = new DateTime(2020, 12, 7, 14, 25, 2, 209, DateTimeKind.Local).AddTicks(7739),
                            ReceiveUserID = 2
                        });
                });

            modelBuilder.Entity("HW.Host.API.Model.ModelEntity.HW_PhoneReceiveInfo", b =>
                {
                    b.HasOne("HW.Host.API.Model.ModelEntity.HW_PhoneModelInfo", "HW_PhoneModelInfo")
                        .WithMany()
                        .HasForeignKey("ReceivePhoneModelID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HW.Host.API.Model.DefaultEntity.HW_Users", "HW_Users")
                        .WithMany()
                        .HasForeignKey("ReceiveUserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
